version: "3"
services:
  admin:
    image: jamesemwallis/admin
    container_name: admin
    ports:
      - 5000:4050
    environment:
     - ADMIN_USERNAME=admin
     - ADMIN_PASSWORD=admin
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock/
